---
title: "Untitled"
author: "Enrique Otanez"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DBI)
library(sqldf)
library(dplyr)
library(neuralnet)
library(Metrics)
library(caret)
library(config)
library(datapackage.r)
library(jsonlite)
library(fastDummies)
library(datarium)
library(ggplot2)


get_data <- function(scores_or_new, server, user, password, database, port){
  library(odbc)
  con <- DBI::dbConnect(odbc::odbc(),
                        driver = "PostgreSQL Unicode(x64)",
                        database = as.character(database),
                        UID      = as.character(user),
                        PWD      = as.character(password),
                        server = as.character(server),
                        port = port)
  import.building <- 'SELECT
    bld."CS_ID"
    ,avg(bs."Score") "Average Building Score"
    ,bld."Address_Line"
    ,bld."City"
    ,bld."Postal_Code"
    ,bld."Property_Type"
    ,bld."Year_Built"
    ,bld."Price"
    ,bld."SquareFeet"
    ,round(cast(coalesce(bld."Price" / bld."SquareFeet",NULL) as numeric),0) "$ per sq ft"
     ,bld."Sale_Type"
     ,bg.bg_geo_id "Block Group ID"
     ,avg(bgs.score) "Average Block Group Score"
     ,max(case when dv.sid=\'pop\' then bgd.value Else 0 END) "Population"
     ,max(case when dv.sid=\'pop_MF_3MS\' then bgd.value Else 0 END) "Population: 3 Miles"
     ,max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) "Households: 3 Miles"
    ,max(case when dv.sid=\'M_0_5\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_0_5\' then bgd.value Else 0 END) "Kids under 5"
     ,round(cast((max(case when dv.sid=\'M_0_5\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_0_5"\' then bgd.value Else 0 END)) /
        max(case when dv.sid=\'pop\' then bgd.value Else null END) as numeric),3) "Percent Kids under 5"
    ,max(case when dv.sid=\'M_0_5_3MS\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_0_5_3MS\' then bgd.value Else 0 END) "Kids under 5: 3 Miles"
     ,round(cast((max(case when dv.sid=\'M_0_5_3MS\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_0_5_3MS\' then bgd.value Else 0 END)) /
        max(case when dv.sid=\'pop_MF_3MS\' then bgd.value Else null END) as numeric),3) "Percent Kids under 5: 3 Miles"
    ,max(case when dv.sid=\'M_5_9\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_5_9\' then bgd.value Else 0 END) "Kids 5 to 9"
     ,round(cast((max(case when dv.sid=\'M_5_9\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_5_9\' then bgd.value Else 0 END)) /
        max(case when dv.sid=\'pop\' then bgd.value Else null END) as numeric),3) "Percent Kids 5 to 9"
    ,max(case when dv.sid=\'M_5_9_3MS\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_5_9_3MS\' then bgd.value Else 0 END) "Kids 5 to 9: 3 Miles"
    ,round(cast((max(case when dv.sid=\'M_5_9_3MS\' then bgd.value Else 0 END)+max(case when dv.sid=\'F_5_9_3MS\' then bgd.value Else 0 END)) /
         max(case when dv.sid=\'pop_MF_3MS\' then bgd.value Else null END) as numeric),3)  "Percent Kids 5 to 9: 3 Miles"
    ,max(case when dv.sid=\'avg_age\' then bgd.value Else 0 END) "Average Age"
    ,round(cast(sum(case when dv.sid in(\'hi_0_10_3MS\',\'hi_10_15_3MS\',\'hi_15_20_3MS\',\'hi_20_25_3MS\',\'hi_25_30_3MS\',\'hi_30_35_3MS\',\'hi_35_40_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income under 40K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_40_45_3MS\',\'hi_45_50_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 40K to 50K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_50_60_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 50K to 60K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_60_75_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 60K to 75K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_75_100_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 75K to 100K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_100_125_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 100K to 125K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_125_150_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 125K to 150K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_150_200_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 150K to 200K: 3 Mile"
    ,round(cast(sum(case when dv.sid in(\'hi_200_999_3MS\') then bgd.value  else 0 END) /
      max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) as numeric),3) "Household income 200K+: 3 Mile"
from "Building" as bld
left join "Block_Group" as bg on bg.bg_geo_id = bld.bg_geo_id
left join "BG_Data" as bgd on bg.bg_geo_id = bgd.bg_geo_id
inner join "Demo_Var" as dv on dv.full_variable_id=bgd.variable_id
left join "BG_Score" as bgs on bg.bg_geo_id = bgs.bg_geo_id
left join "Building_Score" as bs on bld."CS_ID" = bs.cs_id
group by bld."CS_ID",bld."Address_Line",bld."City",bld."Postal_Code",bld."Property_Type",bld."Price",bld."Year_Built",bld."SquareFeet",bld."Sale_Type",bg.bg_geo_id
having
    max(case when dv.sid=\'pop\' then bgd.value Else 0 END) > 0
    and max(case when dv.sid=\'hi_tot_3MS\' then bgd.value Else 0 END) > 0;'
  
  building.import <- dbGetQuery(con,import.building)
  
  if(scores_or_new == 'scores'){
    building.scores <- sqldf('SELECT CS_ID, "Average Building Score", Address_Line, City, Postal_Code, Property_Type, Year_Built, Price, SquareFeet, "$ per sq ft", Sale_Type FROM "building.import" WHERE "Average Building Score" IS NOT NULL')
    return(building.scores)
  }
  if(scores_or_new == 'new'){
    building.new <- sqldf('SELECT CS_ID, "Average Building Score", Address_Line, City, Postal_Code, Property_Type, Year_Built, Price, SquareFeet, "$ per sq ft", Sale_Type FROM "building.import" WHERE "Average Building Score" IS NULL') 
    return(building.new)
  }
  if(scores_or_new == 'all'){
    building.all <- sqldf('SELECT CS_ID, "Average Building Score", Address_Line, City, Postal_Code, Property_Type, Year_Built, Price, SquareFeet, "$ per sq ft", Sale_Type FROM "building.import"') 
    return(building.all)
  }
  return("")
}

test.scores <- get_data('scores', 'greentrike.cfvgdrxonjze.us-west-2.rds.amazonaws.com', 'boopbooboobop', 'boobooboobeep', 'TEST', 5432)
test.new <- get_data('new', 'greentrike.cfvgdrxonjze.us-west-2.rds.amazonaws.com', 'noyoumean', 'bopboobooboobopbooboobeep', 'TEST', 5432)
test.scores
test.new
```

```{r}
clean_building_data_scores <- function(dataframe){
  build.scores <- dataframe
  #build.scores$Score <- as.factor(build.scores$Score)
  #dummy code catigorical variables
  build.scores <- fastDummies::dummy_cols(build.scores, select_columns = "City")
  build.scores <- fastDummies::dummy_cols(build.scores, select_columns = "Postal_Code")
  build.scores <- fastDummies::dummy_cols(build.scores, select_columns = "Property_Type")
  build.scores <- fastDummies::dummy_cols(build.scores, select_columns = "Sale_Type")
  #rename select columns for modeling purposes
  names(build.scores)[names(build.scores) == "$ per sq ft"] <- "price_per_sq_ft"
  names(build.scores)[names(build.scores) == "Sale_Type_Investment or Owner User"] <- "Sale_Type_Investment_or_Owner_User"
  names(build.scores)[names(build.scores) == "Sale_Type_Owner User"] <- "Sale_Type_Owner_User"
  names(build.scores)[names(build.scores) == "City_Gig Harbor"] <- "City_Gig_Harbor"
  names(build.scores)[names(build.scores) == "Average Building Score"] <- "Average_Building_Score"
  #subset the data so it does not contain any useless variables
  building.scores <- subset(build.scores, select = c(CS_ID, Average_Building_Score, Address_Line, Price, SquareFeet, price_per_sq_ft, City_Fife, City_Gig_Harbor,   City_Lakewood, City_Puyallup, City_Spanaway, City_Tacoma, Property_Type_Flex, Property_Type_Industrial, Property_Type_Office, Property_Type_Retail,               Sale_Type_Investment, Sale_Type_Investment_or_Owner_User, Sale_Type_Owner_User, Sale_Type_OwnerUser))

  non_na <- complete.cases(building.scores[, c("Address_Line", "Price", "SquareFeet", "price_per_sq_ft", "City_Fife", "City_Gig_Harbor", "City_Lakewood",           "City_Puyallup", "City_Spanaway", "City_Tacoma", "Property_Type_Flex", "Property_Type_Industrial", "Property_Type_Office",                                        "Property_Type_Retail", "Sale_Type_Investment", "Sale_Type_Investment_or_Owner_User", "Sale_Type_Owner_User", "Sale_Type_OwnerUser")])
  out <- building.scores[non_na, ]
  #normalize numeric variables
  out$Price <- (out$Price - min(out$Price))/(max(out$Price) - min(out$Price))
  out$SquareFeet <- (out$SquareFeet - min(out$SquareFeet))/(max(out$SquareFeet) - min(out$SquareFeet))
  out$price_per_sq_ft <- (out$price_per_sq_ft - min(out$price_per_sq_ft))/(max(out$price_per_sq_ft) - min(out$price_per_sq_ft))
  out$Average_Building_Score <- (out$Average_Building_Score - min(out$Average_Building_Score                                                                        ))/(max(out$Average_Building_Score) - min(out$Average_Building_Score))
  #remove duplicates
  out <- out[!duplicated(out[ , "Price"]),]
  
  return(out)
}

  test.clean.scores <- clean_building_data(test.scores)
test.clean.new <- clean_building_data(test.new)
test.clean.scores
test.clean.new
```


```{r}
nn.model.score <- function(data){
    #insert model
    set.seed(3)
    build.new.model <- neuralnet(Average_Building_Score ~ Price + SquareFeet + City_Tacoma + City_Puyallup + Property_Type_Industrial + 
                                 Property_Type_Office + Sale_Type_Investment + Sale_Type_Investment_or_Owner_User + Sale_Type_Owner_User, 
                               data = data, linear.output = T, hidden = c(5,1), act.fct = "logistic")
    #extract scores and set scale 1-5
    predicted.scores <- prediction(build.new.model)
    predict.scores <- predicted.scores$rep1[,10]
    norm.predict.scores <- predict.scores * 5
    Scores.predict <- data.frame(data$CS_ID, norm.predict.scores)
    return(Scores.predict)
}

test.clean.scores.model <- nn.model(test.clean.scores)
test.clean.model
```
```{r}
nn.model.new <- function(server, user, password, database, port, data){
  got_scores_data <- get_data("scores", as.character(server), as.character(user), as.character(password), as.character(database), port)
  cleaned.scores.data <- clean_building_data(got_scores_data)
    #insert model
    set.seed(3)
    build.new.model <- neuralnet(Average_Building_Score ~ Price + SquareFeet + City_Tacoma + City_Puyallup + Property_Type_Industrial + 
                                 Property_Type_Office + Sale_Type_Investment + Sale_Type_Investment_or_Owner_User + Sale_Type_Owner_User, 
                               data = cleaned.scores.data, linear.output = T, hidden = c(5,1), act.fct = "logistic")
    return(build.new.model)
}

test.model.new <- nn.model.new('greentrike.cfvgdrxonjze.us-west-2.rds.amazonaws.com', 'imtellingyoudude', 'ihearditright', 'TEST', 5432)
test.model.new
```

```{r}

new.predictions <- function(data1, data2){
  Scores.predict.new <- predict(data1, data2, all.units = FALSE)
  return(Scores.predict.new)
}
```

```{r}
mainfunction.scores <- function(server, user, password, database, port){
  #get the three types of data
  got_scores_data <- get_data("scores", as.character(server), as.character(user), as.character(password), as.character(database), port)
  #got_new_data <- get_data("new", as.character(server), as.character(user), as.character(password), as.character(database), port)
  #got_all_data <- get_data("all", as.character(server), as.character(user), as.character(password), as.character(database), port)
  #clean the three types of data
  clean.scores.data <- clean_building_data(got_scores_data)
  #clean.new.data <- clean_building_data(got_new_data)
  #clean.all.data <- clean_building_data(got_all_data)
  #score the three types of data
  score.model <- nn.model(clean.scores.data)
  #Scores.predict <- Scores.predict(score.model)
  #scores.predict.new <- nn.model(clean.new.data)
 # scores.predict.all <- nn.model(clean.all.data)
  #neuralnet.scores <- build.new.model(got_scores_data, got_new_data, got_all_data)
  return(score.model)
}

#test.final <- mainfunction(test.clean.model)

mainfunction('greentrike.cfvgdrxonjze.us-west-2.rds.amazonaws.com', 'itsbopbeebeebopboo', 'ithinkilostit', 'TEST', 5432)
```
```{r}
subfunction.new <- function(server, user, password, database, port){
  got_scores_data <- get_data("scores", as.character(server), as.character(user), as.character(password), as.character(database), port)
  clean.scores.data <- clean_building_data(got_scores_data)
  sub.model <- nn.model.new(clean.scores.data)
  return(sub.model)
}

subfunction.new(test.clean.scores)
```

```{r}
mainfunction.new <- function(server, user, password, database, port){
  #get the data
  #got_scores_data <- get_data("scores", as.character(server), as.character(user), as.character(password), as.character(database), port)
  got_new_data <- get_data("new", as.character(server), as.character(user), as.character(password), as.character(database), port)
  #clean the data
  #clean.scores.data <- clean_building_data(got_scores_data)
  clean.new.data <- clean_building_data(got_new_data)
  #load in the subfunction
  model.new <- nn.model.new('greentrike.cfvgdrxonjze.us-west-2.rds.amazonaws.com', 'itoldyoududeits', 'beebeebeebopbopbooboo', 'TEST', 5432)
  #predict with scores first
  #scores.predict.scores <- nn.model.new(clean.scores.data)
  #then predict with new
  Scores.predict.new <- new.predictions(model.new, clean.new.data)
  return(Scores.predict.new)
}

mainfunction.new('greentrike.cfvgdrxonjze.us-west-2.rds.amazonaws.com', 'beepboopbop', 'ithinkilostittoo', 'TEST', 5432)
```

