---
title: "New_Data_NeuNet"
author: "Enrique Otanez"
date: "3/7/2021"
output: word_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet"))
```

```{r}
setwd("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet")

#### Table 11.2
library(neuralnet)
library(tidyverse)
new_building <- read.csv("Building.csv")

#Here is the best model for buildings, below are the other models tested. 

new_building$Tacoma <- new_building$City == "Tacoma"
new_building$Puyallup <- new_building$City == "Puyallup"
new_building$Land <- new_building$Property_Type == "Land"
new_building$Multifamily <- new_building$Property_Type == "Multifamily"
new_building$Industrial <- new_building$Property_Type == "Industrial"
new_building$Office <- new_building$Property_Type == "Office"
new_building$Retail <- new_building$Property_Type == "Retail"
new_building$Investment <- new_building$Sale_Type == "Investment"
new_building$OwnerUser <- new_building$Sale_Type == "OwnerUser"
new_building$InvestmentNNN <- new_building$Sale_Type == "InvestmentNNN"
new_building$Investment_or_Owner_User <- new_building$Sale_Type == "Investment or Owner User"

#df$Acceptance <- as.factor(df$Acceptance)
#df$Like <- as.factor(df$Like)
#$Dislike <- as.factor(df$Dislike)

new_building


#in the dataset, I am imputing for the missing prices and I will be removing the rows that does not have squarefeet and price per square feet. After realizing that there is an accuracy issue with finding price per square feet of land vs what would be of a building on the land, they will be removed.


new_building$Price <- (new_building$Price - min(new_building$Price))/(max(new_building$Price) - min(new_building$Price))
new_building$SquareFeet <- (new_building$SquareFeet - min(new_building$SquareFeet))/(max(new_building$SquareFeet) - min(new_building$SquareFeet))
new_building$Price.SQFT <- (new_building$Price.SQFT - min(new_building$Price.SQFT))/(max(new_building$Price.SQFT) - min(new_building$Price.SQFT))
new_building$Tacoma <- new_building$Tacoma*1
new_building$Puyallup <- new_building$Puyallup*1
new_building$Land <- new_building$Land*1
new_building$Multifamily <- new_building$Multifamily*1
new_building$Industrial <- new_building$Industrial*1
new_building$Office <- new_building$Office*1
new_building$Retail <- new_building$Retail*1
new_building$Investment <- new_building$Investment*1
new_building$OwnerUser <- new_building$OwnerUser*1
new_building$InvestmentNNN <- new_building$InvestmentNNN*1
new_building$Investment_or_Owner_User <- new_building$Investment_or_Owner_User*1

#check for duplicates
duplicated(new_building$Price)

#remove rows with duplicates
new_building <- new_building[!duplicated(new_building[ , "Price"]),]

view(new_building)

#check for NA's
str(new_building)
sum(is.na(new_building$Price))
sum(is.na(new_building$SquareFeet))
sum(is.na(new_building$Price.SQFT))



#remove columns
#drop <- c("X", "X.1", "X.2", "X.3", "X.4", "X.5")
#new_building = new_building[,!(names(new_building)%in% drop)]

#new_building needs a blank column
library(tibble)
library(dplyr)

#load model
load(file="buildingneunetmodel")

building_predictions <- predict(bld_neun, new_building, reps = 10, all.units = FALSE)

building_predictions

og_buildings <- read.csv("NeuralNetSet.csv")

setwd("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet")
new_building_for_csv <- read.csv("Building.csv")

#check for duplicates
duplicated(new_building_for_csv$Price)

#remove rows with duplicates
new_building_for_csv <- new_building_for_csv[!duplicated(new_building_for_csv[ , "Price"]),]


new_building_for_csv

#denormalize predicted score
Score.Predict <- building_predictions * (max(og_buildings$Score)-min(og_buildings$Score)) + min(og_buildings$Score)
Score.Predict

final_building <- cbind(new_building_for_csv, Score.Predict)

final_building

setwd("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet")
write.csv(final_building, "D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet\\Enrique_Building_Score.csv", row.names = FALSE)
```

```{r}
#We do the exact same process as building for census
setwd("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet")

new_census <- read.csv("New_Census.csv")

new_census





#here is the best model for census, other models are found below.


#check for duplicates
duplicated(new_census$Block.Group.ID)

#remove rows with duplicates
new_census <- new_census[!duplicated(new_census[ , "Block.Group"]),]

new_census


str(new_census)

#Change all variables into a single scale
#This is because percentages cannot compare to whole numbers and vice versa, its best to just normalize everything
new_census$Population <- (new_census$Population - min(new_census$Population))/(max(new_census$Population) - min(new_census$Population))

new_census$Population..3.Miles <- (new_census$Population..3.Miles - min(new_census$Population..3.Miles))/(max(new_census$Population..3.Miles) - min(new_census$Population..3.Miles))

new_census$Households..3.Miles <- (new_census$Households..3.Miles - min(new_census$Households..3.Miles))/(max(new_census$Households..3.Miles) - min(new_census$Households..3.Miles))

new_census$Kids.under.5 <- (new_census$Kids.under.5 - min(new_census$Kids.under.5))/(max(new_census$Kids.under.5) - min(new_census$Kids.under.5))

new_census$Kids.under.5..3.Miles <- (new_census$Kids.under.5..3.Miles - min(new_census$Kids.under.5..3.Miles))/(max(new_census$Kids.under.5..3.Miles) - min(new_census$Kids.under.5..3.Miles))

new_census$Kids.5.to.9 <- (new_census$Kids.5.to.9 - min(new_census$Kids.5.to.9))/(max(new_census$Kids.5.to.9) - min(new_census$Kids.5.to.9))

new_census$Kids.under.5..3.Miles <- (new_census$Kids.under.5..3.Miles - min(new_census$Kids.under.5..3.Miles))/(max(new_census$Kids.under.5..3.Miles) - min(new_census$Kids.under.5..3.Miles))

new_census$Average.Age <- (new_census$Average.Age - min(new_census$Average.Age))/(max(new_census$Average.Age) - min(new_census$Average.Age))

new_census$Household.income.under.40K..3.Mile <- (new_census$Household.income.under.40K..3.Mile - min(new_census$Household.income.under.40K..3.Mile))/(max(new_census$Household.income.under.40K..3.Mile) - min(new_census$Household.income.under.40K..3.Mile))

new_census$Household.income.40K.to.50K..3.Mile <- (new_census$Household.income.40K.to.50K..3.Mile - min(new_census$Household.income.40K.to.50K..3.Mile))/(max(new_census$Household.income.40K.to.50K..3.Mile) - min(new_census$Household.income.40K.to.50K..3.Mile))

new_census$Household.income.50K.to.60K..3.Mile <- (new_census$Household.income.50K.to.60K..3.Mile - min(new_census$Household.income.50K.to.60K..3.Mile))/(max(new_census$Household.income.50K.to.60K..3.Mile) - min(new_census$Household.income.50K.to.60K..3.Mile))

new_census$Household.income.60K.to.75K..3.Mile <- (new_census$Household.income.60K.to.75K..3.Mile - min(new_census$Household.income.60K.to.75K..3.Mile))/(max(new_census$Household.income.60K.to.75K..3.Mile) - min(new_census$Household.income.60K.to.75K..3.Mile))

new_census$Household.income.75K.to.100K..3.Mile <- (new_census$Household.income.75K.to.100K..3.Mile - min(new_census$Household.income.75K.to.100K..3.Mile))/(max(new_census$Household.income.75K.to.100K..3.Mile) - min(new_census$Household.income.75K.to.100K..3.Mile))

new_census$Household.income.100K.to.125K..3.Mile <- (new_census$Household.income.100K.to.125K..3.Mile - min(new_census$Household.income.100K.to.125K..3.Mile))/(max(new_census$Household.income.100K.to.125K..3.Mile) - min(new_census$Household.income.100K.to.125K..3.Mile))

new_census$Household.income.125K.to.150K..3.Mile <- (new_census$Household.income.125K.to.150K..3.Mile - min(new_census$Household.income.125K.to.150K..3.Mile))/(max(new_census$Household.income.125K.to.150K..3.Mile) - min(new_census$Household.income.125K.to.150K..3.Mile))

new_census$Household.income.150K.to.200K..3.Mile <- (new_census$Household.income.150K.to.200K..3.Mile - min(new_census$Household.income.150K.to.200K..3.Mile))/(max(new_census$Household.income.150K.to.200K..3.Mile) - min(new_census$Household.income.150K.to.200K..3.Mile))

new_census$Household.income.200K...3.Mile <- (new_census$Household.income.200K...3.Mile - min(new_census$Household.income.200K...3.Mile))/(max(new_census$Household.income.200K...3.Mile) - min(new_census$Household.income.200K...3.Mile))

#census$Area.Score <- (census$Area.Score - min(census$Area.Score))/(max(census$Area.Score) - min(census$Area.Score))
view(new_census)


#set the scale to -1:1
#set scale from 0 to 1 to -1 to 1
new_census$Population <- (2 * ((new_census$Population - min(new_census$Population))/max(new_census$Population) - min(new_census$Population))) - 1
new_census$Population..3.Miles <- (2 * ((new_census$Population..3.Miles - min(new_census$Population..3.Miles))/max(new_census$Population..3.Miles) - min(new_census$Population..3.Miles))) - 1
new_census$Households..3.Miles <- (2 * ((new_census$Households..3.Miles - min(new_census$Households..3.Miles))/max(new_census$Households..3.Miles) - min(new_census$Households..3.Miles))) - 1
new_census$Kids.under.5 <- (2 * ((new_census$Kids.under.5 - min(new_census$Kids.under.5))/max(new_census$Kids.under.5) - min(new_census$Kids.under.5))) - 1
new_census$Kids.under.5..3.Miles <- (2 * ((new_census$Kids.under.5..3.Miles - min(new_census$Kids.under.5..3.Miles))/max(new_census$Kids.under.5..3.Miles) - min(new_census$Kids.under.5..3.Miles))) - 1
new_census$Kids.5.to.9 <- (2 * ((new_census$Kids.5.to.9 - min(new_census$Kids.5.to.9))/max(new_census$Kids.5.to.9) - min(new_census$Kids.5.to.9))) - 1
new_census$Kids.5.to.9..3.Miles <- (2 * ((new_census$Kids.5.to.9..3.Miles - min(new_census$Kids.5.to.9..3.Miles))/max(new_census$Kids.5.to.9..3.Miles) - min(new_census$Kids.5.to.9..3.Miles))) - 1
new_census$Average.Age <- (2 * ((new_census$Average.Age - min(new_census$Average.Age))/max(new_census$Average.Age) - min(new_census$Average.Age))) - 1
new_census$Household.income.under.40K..3.Mile <- (2 * ((new_census$Household.income.under.40K..3.Mile - min(new_census$Household.income.under.40K..3.Mile))/max(new_census$Household.income.under.40K..3.Mile) - min(new_census$Household.income.under.40K..3.Mile))) - 1
new_census$Household.income.40K.to.50K..3.Mile <- (2 * ((new_census$Household.income.40K.to.50K..3.Mile - min(new_census$Household.income.40K.to.50K..3.Mile))/max(new_census$Household.income.40K.to.50K..3.Mile) - min(new_census$Household.income.40K.to.50K..3.Mile))) - 1
new_census$Household.income.50K.to.60K..3.Mile <- (2 * ((new_census$Household.income.50K.to.60K..3.Mile - min(new_census$Household.income.50K.to.60K..3.Mile))/max(new_census$Household.income.50K.to.60K..3.Mile) - min(new_census$Household.income.50K.to.60K..3.Mile))) - 1
new_census$Household.income.60K.to.75K..3.Mile <- (2 * ((new_census$Household.income.60K.to.75K..3.Mile - min(new_census$Household.income.60K.to.75K..3.Mile))/max(new_census$Household.income.60K.to.75K..3.Mile) - min(new_census$Household.income.60K.to.75K..3.Mile))) - 1
new_census$Household.income.75K.to.100K..3.Mile <- (2 * ((new_census$Household.income.75K.to.100K..3.Mile - min(new_census$Household.income.75K.to.100K..3.Mile))/max(new_census$Household.income.75K.to.100K..3.Mile) - min(new_census$Household.income.75K.to.100K..3.Mile))) - 1
new_census$Household.income.100K.to.125K..3.Mile <- (2 * ((new_census$Household.income.100K.to.125K..3.Mile - min(new_census$Household.income.100K.to.125K..3.Mile))/max(new_census$Household.income.100K.to.125K..3.Mile) - min(new_census$Household.income.100K.to.125K..3.Mile))) - 1
new_census$Household.income.125K.to.150K..3.Mile <- (2 * ((new_census$Household.income.125K.to.150K..3.Mile - min(new_census$Household.income.125K.to.150K..3.Mile))/max(new_census$Household.income.125K.to.150K..3.Mile) - min(new_census$Household.income.125K.to.150K..3.Mile))) - 1
new_census$Household.income.150K.to.200K..3.Mile <- (2 * ((new_census$Household.income.150K.to.200K..3.Mile - min(new_census$Household.income.150K.to.200K..3.Mile))/max(new_census$Household.income.150K.to.200K..3.Mile) - min(new_census$Household.income.125K.to.150K..3.Mile))) - 1
new_census$Household.income.200K...3.Mile <- (2 * ((new_census$Household.income.200K...3.Mile - min(new_census$Household.income.200K...3.Mile))/max(new_census$Household.income.200K...3.Mile) - min(new_census$Household.income.200K...3.Mile))) - 1

view(new_census)

new_census

load(file="censusneunetmodel")

new_census.predict <- predict(census_neun, new_census, rep = 10, all.units = FALSE)
new_census.predict


#remove columns
#drop <- c("X", "X.1", "X.2", "X.3", "X.4", "X.5")
#new_building = new_building[,!(names(new_building)%in% drop)]

#new_building needs a blank column
library(tibble)
library(dplyr)

#load model

og_census <- read.csv("NeunetCensusSet.csv")




#to prove that this works
#normalize 0 to 1
og_census$Area.Score.Norm <- (og_census$Area.Score - min(og_census$Area.Score))/(max(og_census$Area.Score) - min(og_census$Area.Score))
og_census$Area.Score.Norm

#0 to 1 to -1 to 1
og_census$Area.Score.NegNorm <- (2 * ((og_census$Area.Score.Norm - min(og_census$Area.Score.Norm))/max(og_census$Area.Score.Norm) - min(og_census$Area.Score.Norm))) - 1
og_census$Area.Score.NegNorm

og_census

#-1 to 1 to 0 to 1
og_census$Area.Score.Predict.Norm <- (og_census$Area.Score.NegNorm-1)*(max(og_census$Area.Score.Norm)-min(og_census$Area.Score.Norm))/2+min(og_census$Area.Score.Norm)
og_census$Area.Score.Predict.Norm

og_census

#0 to 1 to 1- to 5
og_census$Area.Score.Predict <- og_census$Area.Score.Predict.Norm * (max(og_og_census$Area.Score)-min(og_og_census$Area.Score)) + min(og_og_census$Area.Score)
og_census$Area.Score.Predict




















#normalize area.score to help with the denormalization of the predicted score
og_census2$Area.Score <- (og_census2$Area.Score - min(og_census2$Area.Score))/(max(og_census2$Area.Score) - min(og_census2$Area.Score))
og_census2$Area.Score

setwd("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet")
new_census_for_csv <- read.csv("New_Census.csv")


#denormalize predicted score (-1:1) to (0:1)
unnomtanh <- ((new_census.predict-1)*(max(og_census2$Area.Score)-min(og_census2$Area.Score)))/2+min(og_census2$Area.Score)
unnomtanh


#denormalize
Area.Score.Predict <- unnomtanh * (max(og_census$Area.Score)-min(og_census$Area.Score)) + min(og_census$Area.Score)
Area.Score.Predict

final_building <- cbind(new_building_for_csv, Score.Predict)

final_building

setwd("D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet")
write.csv(final_building, "D:/Templates/UW Stuff/Classes/MSBA/Classes/PM Stuff for me/NeuralNet\\Enrique_Building_Score.csv", row.names = FALSE)
```

